export const InfosList = [
  {
    id: 0,
    title: "UrBuy",
    tag: "urbuy",
    description: "Um aplicativo de e-commerce desenvolvido em react native para facilitar a compra de produtos do ramo de tecnologia.",
    techs: [
      "reactNative",
      "typescript",
      "tailwind",
      "react"
    ],
    linkGithub: "https://github.com/AugustoCVS/UrBuy-mobile",
    linkProject: "https://github.com/AugustoCVS/UrBuy-mobile",
    dataAos: "fade-right",
  },
  {
    id: 1,
    title: "Rick and Morty",
    tag: "rickAndMorty",
    description: "Aplicação de consulta, visualização e listagem dos seus personagens favoritos do seriado Rick & Morty.",
    techs: [
      "angular",
      "typescript",
      "sass",
    ],
    linkGithub: "https://github.com/AugustoCVS/RickAndMorty",
    linkProject: "https://rick-and-morty-two-psi.vercel.app",
    dataAos: "fade-left",
  },
  {
    id: 2,
    title: "Portfólio",
    tag: "portfolio",
    description: "Portfólio desenvolvido em ReactJS para apresentar meus projetos e habilidades.",
    techs: [
      "react",
      "typescript",
      "sass",
    ],
    linkGithub: "https://github.com/AugustoCVS/new-portfolio",
    linkProject: "https://main--agtportfolio.netlify.app",
    dataAos: "fade-right",
  },
  {
    id: 3,
    title: "Store",
    tag: "store",
    description: "Página inicial de e-commerce desenvolvida em nextjs com integração com uma api de ecommerce para listagem de produtos e carrinho de compras. 97% de test coverage.",
    techs: [
      "next",
      "typescript",
      "styledComponents",
      "redux",
      "jest",
    ],
    linkGithub: "https://github.com/AugustoCVS/store",
    linkProject: "https://cvsstore.netlify.app",
    dataAos: "fade-left",
  },
  {
    id: 4,
    title: "Finnace Controller",
    tag: "finnance",
    description: "Um sistema de controle financeiro desenvolvido em NextJs com integração com uma api de finanças para listagem de transações e controle de saldo, podendo adicionar e remover transações, com gráficos para melhor visualização e controle de gastos. (em desenvolvimento)",
    techs: [
      "next",
      "typescript",
      "tailwind",
      "redux",
    ],
    linkGithub: "https://github.com/AugustoCVS/finance-controller",
    linkProject: "https://finance-controller-sepia.vercel.app",
    dataAos: "fade-right",
  },
  {
    id: 5,
    title: "Backend Finnace Controller",
    tag: "finnance",
    description: "API controle financeiro desenvolvido em Express para listagem de transações e controle de saldo, podendo adicionar e remover transações e contas.",
    techs: [
      "nest",
      "typescript",
      "prisma",
      "postgresql",
    ],
    linkGithub: "https://github.com/AugustoCVS/backend-finance-controller",
    linkProject: "https://github.com/AugustoCVS/backend-finance-controller",
    dataAos: "fade-left",
  },
]
